# Generated by Django 2.1.7 on 2019-03-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish']},
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='mohamed'),
            preserve_default=False,
        ),
    ]
