# Generated by Django 2.1.7 on 2019-03-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_blog', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
